services:
  frontend:
    container_name: kanban-board-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /app
      - /app/node_modules
    environment:
      RUNNING_IN_DOCKER: "true"
    ports:
      - "5173:5173"
